### ISSUE TITLE
configs.py", line 120, in parse_seg_args     save_dir_name = "_".join(save_dir_name)，TypeError: sequence item 1: expected str instance, NoneType found

### ISSUE THREAD

**Issue by xiawei20161308104** [LightersWang/3DUNet-BraTS-PyTorch#2]
您好，我最近做nii图像分割，代码报了一个小错目前还没有解决。请问方便联系您邮件吗。我的是  rg16xw@163.com

**Comment by LightersWang** [comment]
Hi xiawei,

The problem is that you didn't specify the dataset name in the run script, you can check your run script. 

Also, I add a default value for --dataset and the change will be updated very soon.

Finally, my email is hrwang20@fudan.edu.cn , feel free to contact me if you have any questions.

**Comment by xiawei20161308104** [comment]
I emailed you a new question, and apologise for the delay.
